- name: Install Nginx
  become: true
  action: apt pkg=nginx state=latest

- name: Enable Nginx service
  action: service name=nginx enabled=yes

- name: create/update the mime types
  become: true
  template:
    src: mime.types.j2
    dest: "{{ DATA_PATH }}/mime.types"

- name: create/update the nginx conf
  become: true
  template:
    src: nginx.conf.j2
    dest: "{{ DATA_PATH }}/nginx.conf"

- name: create tmp directory
  become: true
  file:
    path: "{{ DATA_PATH }}/vhosts"
    state: directory

- name: create/update the host conf
  become: true
  template:
    src: host.conf.j2
    dest: "{{ DATA_PATH }}/vhosts/host.conf"

- name: Recursively change ownership of a directory
  become: true
  file:
    path: /usr/share/nginx
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant

- name: create tmp directory
  file:
    path: /usr/share/nginx/tmp
    state: directory

- name: find dir
  command: ls -lrta /usr/share/nginx
  register: find_files

- name: list files
  debug: var=find_files

- name: test configuration
  become: true
  command: nginx -t
  notify:
    - restart nginx
