- name: Install Nginx
  become: true
  action: apt pkg=nginx state=present update_cache=yes


- name: Enable Nginx service
  action: service name=nginx enabled=yes

- name: create/update the mime types
  become: true
  template:
    src: mime.types.j2
    dest: /etc/nginx/mime.types

- name: create/update the nginx conf
  become: true
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: create tmp directory
  become: true
  file:
    path: /etc/nginx/vhosts
    state: directory

- name: create/update the host conf
  become: true
  template:
    src: host.conf.j2
    dest: /etc/nginx/vhosts/host.conf
    validate: bash -c 'nginx -t -c /dev/stdin <<< "events {worker_connections 1;} http { include %s; }"'
  notify: restart nginx


- name: Recursively change ownership of a directory
  become: true
  file:
    path: /usr/share/nginx
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant

- name: create tmp directory
  file:
    path: /usr/share/nginx/tmp
    state: directory

- name: create/update the host conf
  become: true
  template:
    src: host.conf.j2
    dest: /etc/nginx/vhosts/host.conf
    validate: bash -c 'nginx -t -c /dev/stdin <<< "events {worker_connections 1;} http { include %s; }"'
  notify: restart nginx
