---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible
  - printf "[defaults]\nroles_path = ../roles" > provisioner/tests/ansible.cfg

script:
     - cd provisioner/tests; ansible-playbook -i inventory test.yml --syntax-check
     - "ansible-playbook -i inventory test.yml --connection=local"
     - >
       ansible-playbook -i inventory test.yml --connection=local
       | grep -q 'changed=0.*failed=0'
         &amp;&amp; (echo 'Idempotence test: pass' &amp;&amp; exit 0)
       || (echo 'Idempotence test: fail' &amp;&amp; exit 1)
