---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible
  - printf "[defaults]\nroles_path = ../roles" > provisioner/tests/ansible.cfg

script:
     - cd provisioner/tests; ansible-playbook -i inventory test.yml --syntax-check
