Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.define "lb"
  config.vm.define "webserver1"
  config.vm.define "webserver2"
  

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../provisioner/main.yml"
    ansible.groups = {
      "lb_group" => ["lb"],
      "webservers" => ["webserver[1:2]"],
      "all_groups:children" => ["lb_group", "webservers"]
    }
  end
 
     
end

