Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "lb" do |lb_config|
    lb_config.vm.provider "virtualbox" do |vb|
      vb.memory = 256
      vb.cpus = 1
    end
    lb_config.vm.network "private_network", ip: "172.16.0.10"
    lb_config.vm.network "forwarded_port", guest: 80, host: 80
  end

  config.vm.define "webserver1" do |w1_config|
    w1_config.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
    w1_config.vm.network "private_network", ip: "172.16.0.11"
    w1_config.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "webserver2" do |w2_config|
    w2_config.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end
    w2_config.vm.network "private_network", ip: "172.16.0.12"
    w2_config.vm.network "forwarded_port", guest: 80, host: 8081
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../provisioner/init.yml"
    ansible.verbose = "vvvv"
    ansible.groups = {
      "lb_group" => ["lb"],
      "webservers" => ["webserver[1:2]"],
      "all_groups:children" => ["lb_group", "webservers"]
    }
    ansible.host_vars = {
      "webserver1" => {"http_port" => 8080,
                       "machine_ip" => "172.16.0.11"
                  },
      "webserver2" => {"http_port" => 8081,
                       "machine_ip" => "172.16.0.12"
      }
    }
  end


end
