---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: haproxy
    box: generic/ubuntu1804
    memory: 256
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
    provider_raw_config_args:
      - 'nic_model_type = "virtio"'
      - 'disk_bus = "virtio"'
      - 'volume_cache = "none"'
      - 'storage :file, bus: "virtio", cache: "none"'    
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        children:
          webservers:
            vars:
              ansible_host: webserver1
              machine_ip: "172.16.0.11:80"
verifier:
  name: ansible
