---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: VBox
platforms:
  - name: haproxy
    box: generic/ubuntu1804
    memory: 256
    cpus: 1
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        children:
          webservers:
            vars:
              ansible_host: webserver1
              machine_ip: "172.16.0.11:80"
verifier:
  name: ansible
