---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: lb
    box: generic/ubuntu1804
    memory: 256
    cpus: 1
    instance_raw_config_args:
      - 'vagrant.plugins = ["vagrant-libvirt"]'
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
