---
- name: setup docker on all machines
  hosts: lb_group, webservers
  roles:
     - setup/docker

- name: pull required images
  hosts: lb_group
  roles:
    - setup/pull-docker-images
  vars:
    - images: ['haproxy:1.7']
