- name: Install HAProxy
  become: true
  action: apt pkg=haproxy state=latest

- name: Enable HAProxy service
  action: service name=haproxy enabled=yes

- name: create/update the config
  become: true
  template:
    src: ha.cfg
    dest: "{{ DATA_PATH }}/haproxy.cfg"

- name: test configuration
  command: haproxy -c -V -f {{ DATA_PATH }}/haproxy.cfg
  notify:
    - restart haproxy
