- name: Install HAProxy
  become: true
  action: apt pkg=haproxy state=present update_cache=yes

- name: Enable HAProxy service
  action: service name=haproxy enabled=yes

- name: create/update the config
  become: true
  template:
    src: ha.cfg
    dest: /etc/haproxy/haproxy.cfg
  register: haproxy_config

- name: test configuration
  command: haproxy -c -V -f /etc/haproxy/haproxy.cfg
  changed_when: haproxy_config.changed
  notify:
    - restart haproxy
